import {
  Loader2,
  Mail,
  Lock,
  User,
  LogOut,
  Chrome,
  Home,
  LayoutTemplate,
  Lightbulb,
  Settings,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Search,
  Bell,
  Menu,
  X,
  MoreHorizontal,
  FileSpreadsheet,
  Folder,
  FolderOpen,
  Sparkles,
  Table,
  Trash2,
  Edit3,
  Copy,
  Check,
  AlertCircle,
  Info,
  ExternalLink,
  Moon,
  Sun,
  PanelLeftClose,
  PanelLeft,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  lock: Lock,
  user: User,
  logout: LogOut,
  google: Chrome,
  home: Home,
  template: LayoutTemplate,
  insight: Lightbulb,
  settings: Settings,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  plus: Plus,
  search: Search,
  bell: Bell,
  menu: Menu,
  close: X,
  more: MoreHorizontal,
  sheet: FileSpreadsheet,
  folder: Folder,
  folderOpen: FolderOpen,
  ai: Sparkles,
  table: Table,
  trash: Trash2,
  edit: Edit3,
  copy: Copy,
  check: Check,
  alert: AlertCircle,
  info: Info,
  externalLink: ExternalLink,
  moon: Moon,
  sun: Sun,
  sidebarClose: PanelLeftClose,
  sidebarOpen: PanelLeft,
};

export type IconName = keyof typeof Icons;
